{{- if and .Values.k8s_sensor.deployment.enabled (not .Values.kubernetes.deployment.enabled) -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8sensor
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "instana-agent.commonLabels" . | nindent 4 }}
{{- end }}
