{{- if .Values.k8s_sensor.deployment.enabled -}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k8sensor
  labels:
    {{- include "instana-agent.commonLabels" . | nindent 4 }}
rules:
  - apiGroups: [ "" ]
    resources: [ "configmaps" ]
    verbs: [ "get", "list", "watch" ]

  - apiGroups: [ "" ]
    resources:
      - "events"
      - "daemonsets"
      - "deployments"
      - "endpoints"
      - "jobs"
      - "namespaces"
      - "nodes"
      - "persistentvolumes"
      - "persistentvolumeclaims"
      - "pods"
      - "replicasets"
      - "services"
      - "statefulsets"
    verbs: [ "get", "list", "watch" ]

  - apiGroups: [ "apps" ]
    resources:
      - "daemonsets"
      - "deployments"
      - "replicasets"
      - "statefulsets"
    verbs: [ "get", "list", "watch" ]

  - apiGroups: [ "batch" ]
    resources: [ "cronjobs", "jobs" ]
    verbs: [ "get", "list", "watch" ]

  - apiGroups: [ "" ]
    resources: [ "pods/log" ]
    verbs: [ "get", "list", "watch" ]

  - apiGroups: [ "policy" ]
    resources: [ "podsecuritypolicies" ]
    verbs: [ "use" ]
    resourceNames:
      - k8sensor
{{- end }}
