annotations:
  artifacthub.io/links: |
    - name: Instana website
      url: https://www.ibm.com/products/instana
    - name: Instana Helm charts
      url: https://github.com/instana/helm-charts
apiVersion: v2
appVersion: 1.285.0
description: Instana Agent for Kubernetes
home: https://www.instana.com/
icon: https://agents.instana.io/helm/stan-logo-2020.png
maintainers:
- email: felix.marx@ibm.com
  name: FelixMarxIBM
- email: henning.treu@ibm.com
  name: htreu
- email: konrad.ohms@de.ibm.com
  name: Konrad-Ohms
name: instana-agent
sources:
- https://github.com/instana/instana-agent-docker
version: 2.0.0
